export const TECHNOLOGY_TAXONOMY: Record<string, string[]> = {
    "Java": [
        "Language Basics & Syntax",
        "Data Types, Variables & Type Casting",
        "Operators & Expressions",
        "Conditional Statements & Loops",
        "Arrays & String Handling",
        "Object-Oriented Programming (OOPS)",
        "Classes, Objects & Constructors",
        "Inheritance & Polymorphism",
        "Abstraction & Interfaces",
        "Encapsulation & Access Modifiers",
        "Exception Handling",
        "Java Collections Framework (List, Set, Map, Queue)",
        "Generics",
        "Multithreading & Concurrency",
        "Java 8+ Features (Lambdas, Streams, Optional)",
        "File I/O & Serialization",
        "JVM Architecture & Garbage Collection"
    ],
    "Python": [
        "Syntax, Variables & Dynamic Typing",
        "Built-in Data Types & Type Casting",
        "Control Flow & Iteration",
        "Functions, Scope & *args/**kwargs",
        "Lists, Tuples, Sets & Dictionaries",
        "List, Set & Dictionary Comprehensions",
        "String Formatting & Slicing",
        "Object-Oriented Programming (Classes, Self, Magic Methods)",
        "Inheritance, Polymorphism & Duck Typing",
        "Exception Handling (try-except-finally)",
        "File Handling & Context Managers (with)",
        "Modules, Packages & Virtual Environments",
        "Iterators & Generators",
        "Decorators",
        "Lambda, map, filter & reduce",
        "Memory Management & Garbage Collection"
    ],
    "C++": [
        "Basic Syntax, Primitive Types & Constants",
        "Pointers, Pointer Arithmetic & References",
        "Dynamic Memory Management (new/delete)",
        "Functions, Overloading & Inline Functions",
        "Classes, Objects & Constructors/Destructors",
        "Access Specifiers & Encapsulation",
        "Inheritance & Friend Functions",
        "Polymorphism, Virtual Functions & Pure Virtual Classes",
        "Operator Overloading",
        "Templates (Function & Class Templates)",
        "Standard Template Library (STL Containers & Iterators)",
        "STL Algorithms & Functors",
        "Exception Handling",
        "File I/O with fstream",
        "Smart Pointers (unique_ptr, shared_ptr, weak_ptr)",
        "Move Semantics & Rvalue References"
    ],
    "C Programming": [
        "Structure of a C Program & Compilation Stages",
        "Data Types, Modifiers & Format Specifiers",
        "Operators (Arithmetic, Relational, Logical, Bitwise)",
        "Decision Making (if-else, switch-case)",
        "Loops & Jump Statements (break, continue, goto)",
        "Arrays (1D & Multidimensional)",
        "Strings & String Library Functions (string.h)",
        "Functions, Prototyping & Recursion",
        "Pointers & Memory Addresses",
        "Dynamic Memory Allocation (malloc, calloc, realloc, free)",
        "Structures, Nested Structures & Unions",
        "Typedef & Enumerations",
        "File Handling (fopen, fread, fwrite, fclose)",
        "Preprocessor Directives & Macros (#define, #ifdef)",
        "Storage Classes (auto, static, extern, register)"
    ],
    "JavaScript": [
        "Variables & Declarations (var, let, const)",
        "Data Types & Type Coercion",
        "Operators & Expressions",
        "Functions, Arrow Functions & Hoisting",
        "Scope (Global, Function, Block) & Closures",
        "Arrays & Higher-Order Methods (map, filter, reduce)",
        "Objects, Methods & this Keyword",
        "Prototypes & Prototypal Inheritance",
        "ES6+ Classes & Destructuring",
        "Spread & Rest Operators",
        "DOM Manipulation & Event Handling",
        "Asynchronous JS (Callbacks, Promises, Async/Await)",
        "Event Loop, Microtask Queue & Macrotask Queue",
        "Modules (ESM vs CommonJS)",
        "Error Handling (try-catch-finally)",
        "Web Storage (LocalStorage, SessionStorage, Cookies)"
    ],
    "Advanced SQL": [
        "Complex Joins (Self, Cross, Full Outer)",
        "Correlated & Non-Correlated Subqueries",
        "Window Functions (ROW_NUMBER, RANK, DENSE_RANK, NTILE)",
        "Aggregate Window Functions (LEAD, LAG, FIRST_VALUE)",
        "Common Table Expressions (CTEs) & Recursive CTEs",
        "GROUP BY, HAVING, ROLLUP & CUBE",
        "Set Operators (UNION, INTERSECT, EXCEPT)",
        "Conditional Logic (CASE WHEN)",
        "Stored Procedures & User-Defined Functions (UDFs)",
        "Triggers & Materialized Views",
        "Database Indexing (Clustered, Non-Clustered, B-Tree)",
        "Query Optimization, Execution Plans & EXPLAIN",
        "ACID Properties & Transaction Isolation Levels",
        "Partitioning & Sharding Basics"
    ],
    "MySQL": [
        "Database & Table Creation (DDL)",
        "Data Insertion, Update & Deletion (DML)",
        "Data Retrieval & Filtering (DQL)",
        "Constraints (Primary Key, Foreign Key, Unique, Check, Not Null)",
        "Data Types & Storage Considerations",
        "Built-in String, Numeric & Date/Time Functions",
        "Primary & Foreign Key Relationships",
        "Storage Engines (InnoDB vs MyISAM)",
        "Indexes (Primary, Unique, Composite, Full-Text)",
        "Views & Triggers",
        "Stored Procedures & Functions",
        "Transactions & Locking Mechanisms",
        "User Roles, Permissions & Security (GRANT/REVOKE)",
        "Database Backup & Restore (mysqldump)"
    ],
    "Data Structures": [
        "Time & Space Complexity (Asymptotic Notations)",
        "Arrays & Matrix Operations",
        "Singly, Doubly & Circular Linked Lists",
        "Stacks (Array & Linked List implementations)",
        "Stack Applications (Parentheses Matching, Infix to Postfix)",
        "Queues (Linear, Circular, Double-Ended Queues)",
        "Priority Queues & Binary Heaps",
        "Hash Tables & Hash Collision Resolution",
        "Binary Trees & Tree Traversals (Inorder, Preorder, Postorder)",
        "Binary Search Trees (BST Operations)",
        "Self-Balancing Trees (AVL, Red-Black Trees)",
        "Tries (Prefix Trees)",
        "Graphs (Adjacency Matrix & List representations)",
        "Graph Traversals (Breadth-First Search, Depth-First Search)",
        "Topological Sort & Cycle Detection",
        "Disjoint Set Union (Union-Find)"
    ],
    "Spring Core": [
        "Inversion of Control (IoC) Principle",
        "Dependency Injection (Constructor, Setter, Field)",
        "BeanFactory vs ApplicationContext",
        "Bean Scopes (Singleton, Prototype, Request, Session)",
        "Bean Lifecycle (Initialization, Destruction, Aware interfaces)",
        "XML vs Annotation-based Configuration",
        "Core Annotations (@Component, @Autowired, @Qualifier, @Primary)",
        "Java-Based Configuration (@Configuration, @Bean)",
        "Component Scanning & Stereotype Annotations",
        "Value Injection & Environment Abstraction (@Value, @PropertySource)",
        "Spring Profiles",
        "Spring Expression Language (SpEL)",
        "Aspect-Oriented Programming (AOP - JoinPoint, Pointcut, Advice)"
    ],
    "Spring Boot": [
        "Spring Boot Architecture & Design Philosophy",
        "Spring Boot Starters & Dependency Management",
        "Auto-Configuration Mechanism (@EnableAutoConfiguration)",
        "The @SpringBootApplication Meta-Annotation",
        "application.properties vs application.yml Configuration",
        "Profile-Specific Properties (application-{profile})",
        "SpringApplication Lifecycle & Banner Customization",
        "Command Line Runner & Application Runner",
        "Embedded Web Servers (Tomcat, Jetty, Undertow)",
        "Spring Boot Actuator (Health, Metrics, Endpoints)",
        "Spring Boot DevTools",
        "Fat JAR Packaging & Production Deployments"
    ],
    "Spring MVC": [
        "Front Controller Pattern & DispatcherServlet Flow",
        "@Controller vs @RestController",
        "Request Mapping & HTTP Verbs (@GetMapping, @PostMapping, etc.)",
        "Handling Parameters (@RequestParam, @PathVariable, @RequestHeader)",
        "Handling Payloads (@RequestBody, @ResponseBody)",
        "Model, ModelMap & ModelAndView",
        "Data Binding & Type Conversion",
        "Form Validation (JSR-380, @Valid, BindingResult)",
        "Global Exception Handling (@ControllerAdvice, @ExceptionHandler)",
        "Handler Interceptors & Servlet Filters",
        "Content Negotiation (JSON, XML)",
        "CORS Configuration (@CrossOrigin)"
    ],
    "Spring Data JPA": [
        "Spring Data Architecture & Repository Hierarchy",
        "CrudRepository vs JpaRepository",
        "Derived Query Methods (Keywords & Subject parsing)",
        "Custom Queries using @Query (JPQL vs Native SQL)",
        "Pagination & Sorting (Pageable, Sort, Page, Slice)",
        "Modifying Queries (@Modifying, @Transactional)",
        "Named Parameters (@Param)",
        "Auditing (@CreatedDate, @LastModifiedDate, @EntityListeners)",
        "DTO & Interface Projections",
        "Specifications & Dynamic Filtering (Criteria API)",
        "Database Migrations Integration (Flyway, Liquibase)"
    ],
    "Spring JDBC": [
        "JdbcTemplate Core Operations (Query, Update, Execute)",
        "NamedParameterJdbcTemplate & MapSqlParameterSource",
        "RowMapper vs ResultSetExtractor",
        "Batch Operations with JdbcTemplate",
        "Exception Translation Mechanism (DataAccessException hierarchy)",
        "SimpleJdbcInsert & SimpleJdbcCall",
        "DataSource Configuration & Pooling (HikariCP)",
        "Transaction Management with DataSourceTransactionManager"
    ],
    "Spring ORM": [
        "Spring ORM Architecture & Integration Points",
        "LocalSessionFactoryBean Configuration",
        "LocalContainerEntityManagerFactoryBean Setup",
        "HibernateTemplate & JpaTemplate Usage",
        "PlatformTransactionManager & @Transactional",
        "Transaction Propagation Types (REQUIRED, REQUIRES_NEW, etc.)",
        "Transaction Isolation Levels",
        "Rollback Rules & Read-Only Transactions",
        "Exception Translation for JPA/Hibernate"
    ],
    "REST API": [
        "REST Architectural Principles & Constraints",
        "HTTP Methods (GET, POST, PUT, PATCH, DELETE, OPTIONS)",
        "HTTP Status Codes (2xx, 3xx, 4xx, 5xx)",
        "URI Design & Resource Naming Conventions",
        "Statelessness & Idempotency",
        "Request & Response Payloads (JSON Formatting)",
        "Standardized Error Response Structures",
        "Query Parameters: Pagination, Filtering & Sorting",
        "API Versioning Strategies (URI, Header, Query Param)",
        "HATEOAS Concept & Implementation",
        "Authentication & Authorization (JWT, Bearer Tokens)",
        "API Documentation (OpenAPI 3 / Swagger)",
        "Rate Limiting & Throttling Concepts"
    ],
    "Hibernate": [
        "ORM Concepts & Architecture",
        "SessionFactory, Session & Transaction Lifecycle",
        "Entity Mapping (@Entity, @Table, @Id, @Column)",
        "Primary Key Generation Strategies (Identity, Sequence, UUID)",
        "Entity Relationships (@OneToOne, @OneToMany, @ManyToOne, @ManyToMany)",
        "Cascading Types (ALL, PERSIST, MERGE, REMOVE)",
        "Fetch Strategies (LAZY vs EAGER Loading)",
        "Hibernate Entity Lifecycle States (Transient, Persistent, Detached, Removed)",
        "Hibernate Query Language (HQL)",
        "Criteria API",
        "Caching Strategies (First-Level vs Second-Level Cache)",
        "The N+1 Query Problem & Solutions (JOIN FETCH, Batch Size)",
        "Dirty Checking Mechanism"
    ],
    "Maven": [
        "Project Object Model (pom.xml) Architecture",
        "Standard Directory Layout",
        "Maven Coordinates (groupId, artifactId, version)",
        "Build Lifecycle, Phases & Goals",
        "Dependency Management & Resolution",
        "Transitive Dependencies & Exclusions",
        "Dependency Scopes (compile, provided, runtime, test, system)",
        "Maven Plugins (Surefire, Compiler, Failsafe, Jar)",
        "Parent POM & Multi-Module Project Aggregation",
        "Properties & Resource Filtering",
        "Maven Profiles & Environment Builds",
        "Repositories (Local, Central, Remote/Enterprise)"
    ],
    "JUnit": [
        "Unit Testing Principles & FIRST Properties",
        "JUnit 5 Architecture (Platform, Jupiter, Vintage)",
        "Core Annotations (@Test, @BeforeEach, @AfterEach, @BeforeAll, @AfterAll)",
        "Assertions Library (assertEquals, assertTrue, assertThrows, assertAll)",
        "Assumptions (assumeTrue, assumingThat)",
        "Parameterized Tests (@ParameterizedTest, @ValueSource, @CsvSource, @MethodSource)",
        "Test Lifecycle & Instance Configuration (@TestInstance)",
        "Nested Tests (@Nested)",
        "Execution Ordering (@TestMethodOrder, @Order)",
        "Tagging & Filtering Tests (@Tag)",
        "Disabling Tests (@Disabled)",
        "Integration with Mocking Frameworks (Mockito with JUnit 5)"
    ],
    "Logging": [
        "Logging Concepts & Importance in Production",
        "Logging Facades vs Implementations (SLF4J vs Logback/Log4j2)",
        "Log Levels (TRACE, DEBUG, INFO, WARN, ERROR, FATAL)",
        "Appenders (Console, File, RollingFileAppender)",
        "Log Formats, Pattern Layouts & Converters",
        "Configuration Files (logback.xml, logback-spring.xml, log4j2.xml)",
        "Rolling Policies (Size-based, Time-based)",
        "Mapped Diagnostic Context (MDC) for Request Tracking",
        "Performance Impact & Asynchronous Logging",
        "Logging Exceptions & Stack Traces Properly",
        "Log Rotation, Retention & Archival"
    ]
};

export const ALL_TECHNOLOGIES = Object.keys(TECHNOLOGY_TAXONOMY);